version: 2
updates:
  # ---------- GitHub Actions ----------
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    reviewers:
      - "ctcampbell"
    target-branch: "main"
    commit-message:
      prefix: deps
      prefix-development: chore
    labels:
      - "dependencies"
    groups:
      production-dependencies:
        dependency-type: "production"
      development-dependencies:
        dependency-type: "development"

  # ---------- NPM / JS ----------
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    reviewers:
      - "ctcampbell"
    target-branch: "main"
    commit-message:
      prefix: deps
      prefix-development: chore
    labels:
      - "dependencies"
    groups:
      production-dependencies:
        dependency-type: "production"
      development-dependencies:
        dependency-type: "development"