name: 'Sarif To Security Standard Report'
description: 'Compare a SARIF results file to a security standard CWE list and produce a report'
author: 'GitHub, Inc'
inputs:
  sarifFile:
    required: true
    description: 'The SARIF file to compare'
  cweFile:
    required: true
    description: 'The CWE file to compare'
runs:
  using: 'node16'
  main: 'dist/index.js'
