name: 'codeql-sarif-security-standard-annotator'
description: 'Compare a CodeQL SARIF results file to a security standard CWE list and annotate the SARIF rules with a tag to highlight results applicable to the security standard'
author: 'GitHub, Inc'
inputs:
  sarifFile:
    required: true
    description: 'The CodeQL SARIF result file'
  cweFile:
    required: false
    description: 'The CWE list XML file, defaults to OWASP Top 10 2021'
  securityStandardTag:
    required: false
    description: 'The security standard tag to add to the SARIF file'
    default: 'owasp-top10-2021'
  outputFile:
    required: false
    description: 'The output SARIF file path, defaults to the input SARIF file path'
runs:
  using: 'composite'
  steps:
    - run: echo "${{ github.action_path}} ${{ inputs.sarifFile }}"
    - run: node '${{ github.action_path }}/dist/index.js'
      shell: bash
